# Generated by Django 4.2.4 on 2023-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=200)),
                ('volunteer_lastname', models.CharField(max_length=200)),
                ('volunteer_age', models.IntegerField()),
                ('volunteer_mail', models.CharField(max_length=100)),
                ('volunteer_password', models.CharField(max_length=300)),
            ],
        ),
    ]
