# Generated by Django 4.2.4 on 2023-08-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_rename_organization_dir_organization_organization_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_mail',
            field=models.EmailField(max_length=100),
        ),
    ]
