# Generated by Django 4.2.4 on 2023-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_alter_volunteer_volunteer_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_phone',
            field=models.CharField(max_length=200),
        ),
    ]
