# Generated by Django 4.2.4 on 2023-08-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0005_alter_organization_organization_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='organization_phone',
            new_name='organization_password',
        ),
    ]
