# Generated by Django 4.2.4 on 2023-09-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0007_alter_organization_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_mail',
            field=models.EmailField(max_length=300, unique=True),
        ),
    ]
