# Generated by Django 4.2.4 on 2023-09-12 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0008_alter_organization_organization_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_password',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 8', regex='^.{8}$')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_password',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 8', regex='^.{8}$')]),
        ),
    ]
