# Generated by Django 4.2.4 on 2023-09-12 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0010_alter_volunteer_volunteer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='La edad debe ser mayor a 0.'), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
