# Generated by Django 4.2.4 on 2023-09-17 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0013_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Ingresa un nombre válido')])),
                ('organization_mail', models.EmailField(max_length=300, unique=True)),
                ('organization_address', models.CharField(max_length=800)),
                ('organization_web', models.CharField(max_length=400)),
                ('organization_description', models.TextField(max_length=2000)),
                ('organization_type', models.CharField(max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_phone',
            field=models.CharField(max_length=10),
        ),
    ]
