# Generated by Django 4.2.4 on 2023-09-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0014_organization1_delete_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization1',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidad.manager'),
        ),
    ]
