# Generated by Django 4.2.4 on 2023-09-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0016_tipoorganizacion_manager_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization1',
            name='organization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.tipoorganizacion'),
        ),
    ]
