# Generated by Django 4.2.4 on 2023-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0017_alter_organization1_organization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization1',
            name='organization_type',
            field=models.CharField(choices=[('Derechos Humanos', 'Tipo 1'), ('Medio Ambiente', 'Tipo 2'), ('Salud', 'Tipo 3'), ('Educación', 'Tipo 4'), ('Animales', 'Tipo 5'), ('Cultural y Arte', 'Tipo 6'), ('Alivio de la Pobreza', 'Tipo 7'), ('Derechos de los Refugiados', 'Tipo 8')], max_length=300),
        ),
        migrations.DeleteModel(
            name='TipoOrganizacion',
        ),
    ]
