# Generated by Django 4.2.4 on 2023-09-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0018_alter_organization1_organization_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization1',
            name='organization_type',
            field=models.CharField(choices=[('Tipo 1', 'Derechos Humanos'), ('Tipo 2', 'Medio Ambiente'), ('Tipo 3', 'Salud'), ('Tipo 4', 'Educación'), ('Tipo 5', 'Animales'), ('Tipo 6', 'Cultural y Arte'), ('Tipo 7', 'Alivio de la Pobreza'), ('Tipo 8', 'Derechos de los Refugiados')], max_length=300),
        ),
    ]
