# Generated by Django 4.2.4 on 2023-09-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0019_alter_organization1_organization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization1',
            name='organization_type',
            field=models.CharField(choices=[('Derechos Humanos', 'Derechos Humanos'), ('Medio Ambiente', 'Medio Ambiente'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Animales', 'Animales'), ('Cultural y Arte', 'Cultural y Arte'), ('Alivio de la Pobreza', 'Alivio de la Pobreza'), ('Derechos de los Refugiados', 'Derechos de los Refugiados')], max_length=300),
        ),
    ]
