# Generated by Django 4.2.4 on 2023-09-22 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0021_extendeddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.RemoveField(
            model_name='organization1',
            name='manager',
        ),
        migrations.AddField(
            model_name='organization1',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comunidad.extendeddata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='user_type',
            field=models.CharField(choices=[('V', 'Voluntario'), ('R', 'Representante')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
