# Generated by Django 4.2.4 on 2023-09-23 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0022_delete_volunteer_remove_organization1_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization1',
            name='organization_name',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s,.]*$', 'Ingresa un nombre válido')]),
        ),
    ]
