# Generated by Django 4.2.4 on 2023-09-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0026_alter_interesados_confirmar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesados',
            name='created_date',
        ),
    ]
