# Generated by Django 4.2.4 on 2023-09-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0028_alter_interesados_confirmar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesados',
            name='confirmar',
        ),
        migrations.RemoveField(
            model_name='interesados',
            name='deleted_date',
        ),
        migrations.AddField(
            model_name='interesados',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
