# Generated by Django 4.2.4 on 2023-10-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0031_remove_interesados_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization1',
            name='volunteer_count',
            field=models.CharField(choices=[('1-10', '1 a 10'), ('10-30', '10 a 30'), ('30-50', '30 a 50'), ('+ 50', '+ 50')], max_length=10, null=True),
        ),
    ]
